### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by darkshram** [zibonbadi/lastrange-gtk-theme#1]
I have just discovered your theme and I like it. I would like to make rpm packages and contribute a spec file, but the issue is: Which license does it use?

**Comment by zibonbadi** [comment]
Hi.

Just in case this isn't some sorta timezone-induced late April Fool's, I've now officially licensed it under GPLv3.
Keep in mind that I'm currently unfamiliar with RPM-based distros and as such can't support you regarding that.

However, I would like you to send me your work on said package when you're done so I may advertise it in `README.md`. Likewise feel free to give me pointers on potential oversights in the actual theme.

Best regards,
- Zibon Badi
